# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  namespace: myservices
spec:
  selector:
    matchLabels:
      app: graphql-service
      version: v1
  template:
    metadata:
      labels:
        app: graphql-service
        version: v1
        managed-by: apigee
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: eu.gcr.io/geirs-purdy-project/apigee-graphql:latest
        ports:
        - containerPort: 4000
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep 4000"
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp | fgrep 4000"
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: DEBUG
            value: "true"
          - name: MD_HOST
            value: "masterdataservice"
          - name: MD_PORT
            value: "3000"
          - name: WH_HOST
            value: "warehouseservice"
          - name: WH_PORT
            value: "3000"
          - name: PRICE_HOST
            value: "priceservice"
          - name: PRICE_PORT
            value: "3000"
          - name: CART_HOST
            value: "cartservice"
          - name: CART_PORT
            value: "3000"
          - name: REDIS_HOST
            value: "redis-redis-cluster"
          - name: REDIS_NS
            value: "redis-redis-cluster-headless.redis"
          - name: REDIS_NODES
            value: "6"
          - name: REDIS_PORT
            value: "6379"
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: apisecrets
                key: internalapikey
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redissecrets
                key: redispass
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: myservices
  labels:
    app: graphql-service
spec:
  ports:
  - port: 4000
    name: http
  selector:
    app: graphql-service
