openapi: 3.0.3
info:
  version: 0.0.1
  title: Catalog Service
  description: |
    For fetching a render ready catalog
servers: 
  - url: https://emea-poc15-test.apigee.net/v1
security:
  - ApiKeyAuth: []  
paths:
  '/catalog':
    get:
      summary: 'List `warehouse` objects.'
      description: |
        Fetches list of warehouses of all items we carry
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  persons:
                    type: array
                    items:
                      $ref: '#/components/schemas/ListOfItems'
                  nextPageToken:
                    description: |
                      A token which can be sent as `pageToken`
                      to retrieve the next page.
                    type: string
  '/products':
    get:
      description: 'Retrieve products without pricing'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfItems'
        '404':
          description: 'Item was not found'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
  schemas:
    ListOfItems:
      title: List of warehouses
      type: array
      items:
        $ref: '#/components/schemas/Item'
    Item:
      title: Item
      type: object
      properties:
        name:
          description: |
            name of the item
            Format: `catalog/{itemId}`
          type: string
        number:
          description: 'warehouse stock of an item'
          type: integer
          example: "123"
        price:
          description: 'warehouse stock of an item'
          type: number
        desc:
          description: 'description from masterdata'
          type: string
        imgUrl:
          description: 'Url for an image of the item'
          type: string
        id:
          description: 'uuid of the item in question (internal only)'
          type: string
