openapi: 3.0.3
info:
  version: 0.0.1
  title: warehouse microservice
  description: |
    warehouse microservice
servers: 
  - url: https://devapi.evils.in/
security:
  - ApiKeyAuth: []  
paths:
  '/warehouse':
    get:
      summary: 'List `warehouse` objects.'
      description: |
        Fetches list of warehouses of all items we carry
      # This is an array of GET operation parameters:
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  persons:
                    type: array
                    items:
                      $ref: '#/components/schemas/ListOfItems'
                  nextPageToken:
                    description: |
                      A token which can be sent as `pageToken`
                      to retrieve the next page.
                    type: string
  '/warehouse/{name}':
    get:
      description: 'Retrieve a single Person object.'
      parameters:
        - name: name
          in: path
          description: |
            Unique identifier of the desired person object.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: 'Item was not found'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    ListOfItems:
      title: List of warehouses
      type: array
      items:
        $ref: '#/components/schemas/warehouse'
    Items:
      title: Item
      type: object
      properties:
        name:
          description: |
            name of the item
            Format: `warehouse/{itemId}`
          type: string
        number:
          description: 'warehouse stock of an item'
          type: integer
          example: "123"
        id:
          description: 'uuid of the item in question (internal only)'
          type: string
