apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: apigee-authorization-rule
  namespace: istio-system
spec:
  match: destination.namespace == "default"
  actions:
  - handler: apigee-handler
    instances:
    - apigee.analytics
    - apigee-authorization⇧
