apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: apigee-authorization-rule
  namespace: istio-system
spec:
  match: context.reporter.kind == "inbound" && destination.namespace == "myservices"
  actions:
  - handler: apigee-handler
    instances:
    - apigee-analytics
    - apigee-authorization
